src/AppBundle/Entity/Summoner/RankedStats.php
<?php

namespace AppBundle\Entity\Summoner;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="ranked_stats")
 */
class RankedStats
{
    public function __construct($summonerId, $regionId, $season, $championId)
    {
        $this->summonerId = $summonerId;
        $this->regionId = $regionId;
        $this->season = $season;
        $this->championId = $championId;
    }

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="NONE")
     */
    private $summonerId;

    /**
     * @ORM\Id
     * @ORM\Column(type="smallint")
     * @ORM\GeneratedValue(strategy="NONE")
     */
    private $regionId;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="NONE")
     */
    private $season;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="NONE")
     */
    private $championId;

    /**
     * @ORM\Column(name="wins", type="smallint")
     */
    private $wins;

    /**
     * @ORM\Column(name="loses", type="smallint")
     */
    private $loses;

    /**
     * @ORM\Column(name="kills", type="integer")
     */
    private $kills;

    /**
     * @ORM\Column(name="deaths", type="integer")
     */
    private $deaths;

    /**
     * @ORM\Column(name="assists", type="integer")
     */
    private $assists;

    /**
     * @ORM\Column(name="creeps", type="integer")
     */
    private $creeps;

    /**
     * Get winrate
     *
     * @return float
     */
    public function getWinrate()
    {
        return round(($this->wins / $this->getPlayedGames() * 100), 2);
    }

    /**
     * Get KDA
     *
     * @return float
     */
    public function getKDA()
    {
         return round((($this->kills +  $this->assists) / max(1, $this->deaths)) , 2);
    }

    /**
     * Get KDA
     *
     * @return float
     */
    public function getKillsAVG()
    {
        return round(($this->kills / $this->getPlayedGames()), 1);
    }

    /**
     * Get KDA
     *
     * @return float
     */
    public function getDeathsAVG()
    {
        return round(($this->deaths / $this->getPlayedGames()), 1);
    }

    /**
     * Get KDA
     *
     * @return float
     */
    public function getAssistsAVG()
    {
        return round(($this->assists / $this->getPlayedGames()), 1);
    }

    /**
     * Get KDA
     *
     * @return float
     */
    public function getCreepsAVG()
    {
        return round(($this->creeps / $this->getPlayedGames()), 1);
    }

    /**
     * Set summonerId
     *
     * @param integer $summonerId
     *
     * @return RankedStats
     */
    public function setSummonerId($summonerId)
    {
        $this->summonerId = $summonerId;

        return $this;
    }

    /**
     * Get summonerId
     *
     * @return integer
     */
    public function getSummonerId()
    {
        return $this->summonerId;
    }

    /**
     * Set regionId
     *
     * @param integer $regionId
     *
     * @return RankedStats
     */
    public function setRegionId($regionId)
    {
        $this->regionId = $regionId;

        return $this;
    }

    /**
     * Get regionId
     *
     * @return integer
     */
    public function getRegionId()
    {
        return $this->regionId;
    }

    /**
     * Set season
     *
     * @param integer $season
     *
     * @return RankedStats
     */
    public function setSeason($season)
    {
        $this->season = $season;

        return $this;
    }

    /**
     * Get season
     *
     * @return integer
     */
    public function getSeason()
    {
        return $this->season;
    }

    /**
     * Set championId
     *
     * @param integer $championId
     *
     * @return RankedStats
     */
    public function setChampionId($championId)
    {
        $this->championId = $championId;

        return $this;
    }

    /**
     * Get championId
     *
     * @return integer
     */
    public function getChampionId()
    {
        return $this->championId;
    }

    /**
     * Get playedGames
     *
     * @return integer
     */
    public function getPlayedGames()
    {
        return ($this->wins + $this->loses);
    }

    /**
     * Set wins
     *
     * @param integer $wins
     *
     * @return RankedStats
     */
    public function setWins($wins)
    {
        $this->wins = $wins;

        return $this;
    }

    /**
     * Get wins
     *
     * @return integer
     */
    public function getWins()
    {
        return $this->wins;
    }

    /**
     * Set loses
     *
     * @param integer $loses
     *
     * @return RankedStats
     */
    public function setLoses($loses)
    {
        $this->loses = $loses;

        return $this;
    }

    /**
     * Get loses
     *
     * @return integer
     */
    public function getLoses()
    {
        return $this->loses;
    }

    /**
     * Set kills
     *
     * @param integer $kills
     *
     * @return RankedStats
     */
    public function setKills($kills)
    {
        $this->kills = $kills;

        return $this;
    }

    /**
     * Get kills
     *
     * @return integer
     */
    public function getKills()
    {
        return $this->kills;
    }

    /**
     * Set deaths
     *
     * @param integer $deaths
     *
     * @return RankedStats
     */
    public function setDeaths($deaths)
    {
        $this->deaths = $deaths;

        return $this;
    }

    /**
     * Get deaths
     *
     * @return integer
     */
    public function getDeaths()
    {
        return $this->deaths;
    }

    /**
     * Set assists
     *
     * @param integer $assists
     *
     * @return RankedStats
     */
    public function setAssists($assists)
    {
        $this->assists = $assists;

        return $this;
    }

    /**
     * Get assists
     *
     * @return integer
     */
    public function getAssists()
    {
        return $this->assists;
    }

    /**
     * Set creeps
     *
     * @param integer $creeps
     *
     * @return RankedStats
     */
    public function setCreeps($creeps)
    {
        $this->creeps = $creeps;

        return $this;
    }

    /**
     * Get creeps
     *
     * @return integer
     */
    public function getCreeps()
    {
        return $this->creeps;
    }
}

src/AppBundle/Controller/SummonerController.php
<?php


namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use AppBundle\Entity\Summoner\Summoner;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class SummonerController extends Controller
{

    public function searchAction(Request $request)
    {
        $em = $this->get('doctrine')->getManager();
        $sum = $this->container->get('app.lolsummoner');

        $user = $user = $this->getUser();
        // Si l'utilisateur n'est pas connecté
        if (empty($user)) {
            return $this->render('AppBundle:Lookup:search_error_not_logged_in.html.twig');
        } // Si l'utilisateur n'a pas de summoner enregistré
        else if (count($user->getSummoners()) == 0) {
            return $this->render('AppBundle:Lookup:search_error_no_summoner_registered.html.twig');
        } // Cas normal
        else {
            $region = $sum->getRegionBySlug('euw');
            $minElo = 1;
            $maxElo = 25;
            $sumonnerId = 29233320;
            $search = $em->getRepository('AppBundle:Summoner\Summoner')->findAllSummonersByRegionAndMinEloAndMaxElo($region, $sumonnerId, $minElo, $maxElo);

            return $this->render('AppBundle:Lookup:search.html.twig',
                array(
                    'summoners' => $user->getSummoners(),
                    'search' => $search
                ));
        }
    }

    public function ajaxCreateAction($region, $summonerId)
    {
        $this->container->get('logger')->debug('SummonerId = ' . $summonerId);
        $sum = $this->container->get('app.lolsummoner');

        $response = new Response();
        $response->headers->set('Content-Type', 'application/json');

        try {
            $region = $sum->getRegionBySlug($region);
            $sum->firstUpdateSummoner($region, $summonerId);
            $response->setContent(json_encode(array(
                'status' => 'OK',
            )));
        } catch (\Exception $e) {
            $response->setStatusCode(500);
            $response->setContent(json_encode(array(
                'error' => $e->getMessage(),
            )));
        }

        return $response;
    }

    public function indexAction(Request $request, $region, $summonerId)
    {
        $this->container->get('logger')->debug('SummonerId = ' . $summonerId);
        $em = $this->get('doctrine')->getManager();
        /**  @var \AppBundle\Services\LoLAPI\LoLAPIService $api */
        $api = $this->container->get('app.lolapi');

        /**  @var \AppBundle\Services\SummonerService $sum */
        $sum = $this->container->get('app.lolsummoner');

        $region = $sum->getRegionBySlug($region);

        // On récupère le summoner en BDD
        $summoner = $em->getRepository('AppBundle:Summoner\Summoner')->findOneBy([
            'summonerId' => $summonerId,
            'region' => $region
        ]);

        // Si le summoner n'existe pas encore en BDD, on le crée
        //TODO: Faire ça dans une méthode POST
        if (empty($summoner)) {
            $summonerData = $api->getSummonerBySummonerId($region, $summonerId);
            if ($api->getResponseCode() == 404) {
                //TODO: exception summoner not found
                throw new NotFoundHttpException('Summoner not existing');
            }
            $newSummoner = new Summoner($summonerId, $region);
            $newSummoner->setUser(null);
            $newSummoner->setAccountId($summonerData['accountId']);
            $newSummoner->setName($summonerData['name']);
            $newSummoner->setLevel($summonerData['summonerLevel']);
            $newSummoner->setProfileIconId($summonerData['profileIconId']);
            $date = date_create();
            date_timestamp_set($date, ($summonerData['revisionDate'] / 1000));
            $newSummoner->setRevisionDate($date);
            $em->persist($newSummoner);
            $em->flush();
        } else {
            $newSummoner = $summoner;
        }
        if (empty($summoner) || (!empty($summoner) && !$summoner->isFirstUpdated())) {
            return $this->render('AppBundle:Summoner:creating_summoner.html.twig',
                array(
                    'summoner' => $newSummoner
                ));
        }
        return $this->indexAction3($request, $region->getSlug(), $summonerId);
    }

    public function indexAction3(Request $request, $region, $summonerId)
    {
        $em = $this->get('doctrine')->getManager();
        /**  @var \AppBundle\Services\LoLAPI\LoLAPIService $api */
        $api = $this->container->get('app.lolapi');

        /**  @var \AppBundle\Services\SummonerService $sum */
        $sum = $this->container->get('app.lolsummoner');

        $safeRegion = $em->getRepository('AppBundle:StaticData\Region')->findOneBy([
            'slug' => $region
        ]);
        if (empty($safeRegion)) {
            //TODO: lancer exception
            throw new NotFoundHttpException('Region not existing');
        }

        // On récupère le summoner en BDD
        $summoner = $em->getRepository('AppBundle:Summoner\Summoner')->findOneBy([
            'summonerId' => $summonerId,
            'region' => $safeRegion
        ]);

        // Si le summoner n'existe pas encore en BDD, on le crée
        if (empty($summoner)) {
            $summoner = $api->getSummonerByIds($safeRegion, array($summonerId));
            if ($api->getResponseCode() == 404) {
                //TODO: exception summoner not found
                throw new NotFoundHttpException('Summoner not existing');
            }
            $summonerId = $summoner[$summonerId]['id'];

            $newSummoner = new Summoner($summonerId, $safeRegion);
            $newSummoner->setUser(null);
            $newSummoner->setName($summoner[$summonerId]['name']);
            $newSummoner->setLevel($summoner[$summonerId]['summonerLevel']);
            $newSummoner->setProfileIconId($summoner[$summonerId]['profileIconId']);
            $date = date_create();
            date_timestamp_set($date, ($summoner[$summonerId]['revisionDate'] / 1000));
            $newSummoner->setRevisionDate($date);

            $em->persist($newSummoner);
            $em->flush();
            $summoner = $newSummoner;
        }
        $rankedStats = $sum->getRankedStats($summoner);

        $ranks = $sum->getSummonerRank($safeRegion, $summonerId);
        if (!isset($soloq)) {
            $soloqimg = "unranked_";
        } else {
            $soloqimg = strtolower($soloq['tier']) . '_' . $soloq['entries'][0]['division'];
        }

        $language = $sum->getLanguageByRequestLocale($request);
        $champions = $sum->getChampionsSortedByIds($language);

        //$championsMastery = $sum->updateChampionsMastery($summonerId, $safeRegion);

        /*
        $currentGame = $api->getCurrentGame($summonerId);

        $sumonnerSpellsData = $api->getStaticSummonerSpells();
        $summonerSpells = array();
        foreach($sumonnerSpellsData["data"] as $sumonnerSpell)
        {
            $summonerSpells[$sumonnerSpell["id"]] = $sumonnerSpell["key"];
        }
*/
        /* LIVE GAME */

        //$lg_data = array();
        /*if(isset($currentGame['participants']))
        {
            //var_dump($currentGame['participants'] );exit();
            foreach($currentGame['participants'] as $participant)
            {
                $lg_soloq = $sum->getSummonerRank($participant['summonerId']);
                if(!isset($lg_soloq))
                {
                    $lg_soloqimg = "unranked_";
                }
                else
                {
                    $lg_soloqimg = strtolower($lg_soloq['tier']) . '_' . $lg_soloq['entries'][0]['division'];
                }
                $lg_data[$participant['summonerId']]['rank'] = $lg_soloq;
                $lg_data[$participant['summonerId']]['img'] = $lg_soloqimg;
            }
        }*/
        $topChampionsMasteryData = $api->getChampionsMastery($safeRegion, $summonerId);
        $topChampionsMastery = array();
        // Pour tester avec moins de 3 champion mastery
        //$topChampionsMasteryData = array_slice($topChampionsMasteryData, 0, 3);
        for ($i = 0; $i < count($topChampionsMasteryData) && $i < 3; $i++) {
            $arr = array('championKey' => $champions[$topChampionsMasteryData[$i]['championId']]['key']);
            $topChampionsMastery[$i] = array_merge($topChampionsMasteryData[$i], $arr);
        }

        return $this->render('AppBundle:Summoner:index.html.twig',
            array(
                //'championsMastery' => $championsMastery,
                'topChampionsMastery' => $topChampionsMastery,
                'summoner' => $summoner,
                'ranks' => $ranks,
                'soloqimg' => $soloqimg,
                //'currentGame' => $currentGame,
                //'summonerSpells' => $summonerSpells,
                'champions' => $champions,
                'rankedStats' => $rankedStats,
                //'live_game_data' => $lg_data
            ));
    }
}

src/AppBundle/Resources/views/Summoner/_chests.html.twig
<div class="col-xs-12 col-md-12 white-bg">
    <div class="col-md-12">
        <h2>{{ 'chests'|trans }}</h2>
        <div class="row">
            <div class="col-md-9">
                <div id="chests-choice" class="btn-group">
                    <button data-filter="all" type="button"
                            class="btn btn-primary btn-lg">{{ 'chests.all.champions'|trans }} <span
                                class="badge">{{ champions|length }}</span></button>
                    <button data-filter="1" type="button" class="btn btn-primary btn-lg">{{ 'chests.owned'|trans }}
                        <span
                                class="badge">{{ owned }}</span></button>
                    <button data-filter="2" type="button" class="btn btn-primary btn-lg">{{ 'chests.remaining'|trans }}
                        <span class="badge">{{ remaining }}</button>
                </div>
            </div>
            <div class="col-md-3 input-group">
                <input type="text" name="filtr-search" class="filtr-search form-control" value=""
                       placeholder="{{ 'search'|trans }}" data-search="">
            </div>
        </div>

        <div id="filtr-container-chests" class="filtr-container">
            {% for key, champion in champions %}
                <div class="col-lg-2 col-md-4 col-sm-3 col-xs-2 text-center champion filtr-item" data-category="{{ dataCategory[champion.key] }}"
                     data-sort="value">
                    <h4>{{ champion.name }}</h4>
                    <img src="http://ddragon.leagueoflegends.com/cdn/{{ static_data_version }}/img/champion/{{ champion.key }}.png">
                    {% if champion.chestGranted is defined and champion.chestGranted %}
                        <div>
                            <img src="{{ asset('bundles/app/images/champion-masteries/chest_champion_mastery_over.png' ) }}"/>
                        </div>
                    {% else %}
                        <div>
                            <img src="{{ asset('bundles/app/images/champion-masteries/chest_champion_mastery_disabled.png' ) }}"/>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
</div>

src/AppBundle/Resources/views/Summoner/_history.html.twig
<div class="col-md-12">
    <h2>{{ 'match.history'|trans }}</h2>
    {% for game in history.games %}
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-{% if game.stats.win == 'true' %}success{% else %}danger{% endif %}">
                    <div class="panel-heading">{% if game.stats.win == 'true' %}{{ 'victory'|trans }}{% else %}{{ 'defeat'|trans }}{% endif %} - {{ game.mapId|mapName }} ({{ game.subType|subType }}) - {{ game.stats.timePlayed|duration }}</div>
                    <div class="panel-body h-v-centered">
                        <div class="col-md-2 history-score">
                            <span class="text-success">{{ game.stats.championsKilled }}</span> / <span class="text-danger">{{ game.stats.numDeaths }}</span> / <span class="text-warning">{{ game.stats.assists }}</span>
                        </div>
                        <div class="col-md-7 h-v-centered">
                            <div class="d-inline-block">
                                <img class="history-summoner-champion-icon" src="http://ddragon.leagueoflegends.com/cdn/{{ static_data_version }}/img/champion/{{ champions[game.championId].key }}.png">
                                <br>
                                <img class="history-summoner-spell" src="http://ddragon.leagueoflegends.com/cdn/{{ static_data_version }}/img/spell/{{ summonerSpells[game.spell1] }}.png">
                                <img class="history-summoner-spell" src="http://ddragon.leagueoflegends.com/cdn/{{ static_data_version }}/img/spell/{{ summonerSpells[game.spell2] }}.png">
                            </div>
                            {% for index in 0..6 %}
                                {% include 'AppBundle:Summoner:_history_item.html.twig' with {'item': gamesItems[game.gameId][index] } %}
                            {% endfor %}
                        </div>
                        <div class="col-md-3">
                            <div class="col-md-6">
                                {% for player in gamesPlayers[game.gameId][100] %}
                                    {% include 'AppBundle:Summoner:_history_team_player.html.twig' with {'player': player, 'summoner': summoner} %}
                                {% endfor %}
                            </div>
                            <div class="col-md-6">
                                {% for player in gamesPlayers[game.gameId][200] %}
                                    {% include 'AppBundle:Summoner:_history_team_player.html.twig' with {'player': player } %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

src/AppBundle/Resources/views/Summoner/_live_game.html.twig
{#
<div class="col-md-4">
    {{ currentGame.gameMode }}
</div>
<div class="col-md-4">
    {{ currentGame.mapId }}
</div>
<div class="col-md-4">
    {{ (currentGame.gameLength/60)|round(0, 'floor') }}:{{ currentGame.gameLength%60 }}
</div>
#}
{% include 'AppBundle:Summoner:_live_game_team_table.html.twig' with {'teamCSSId': 'blue_team', 'players': players.blue, 'bannedChampions': bannedChampions.blue} %}
{% include 'AppBundle:Summoner:_live_game_team_table.html.twig' with {'teamCSSId': 'purple_team', 'players': players.purple, 'bannedChampions': bannedChampions.purple} %}
<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>
<style>
    .relative-container {
        position: relative;
    }

    .overlay {
        position: absolute;
        z-index: 100;
    }

    .masteries-background {
        width: 828px;
        height: 479px;
    }

    .masteries {
        width: 50px;
        height: 50px;
        background-repeat: no-repeat;
        background-size: cover
    }

    .masteries-off {
        filter: grayscale(100%);
    }

    .masteries-rank {
        bottom: -15px;
        left: 0;
        color: gold;
        text-align: center;
        width: 50px;
        height: 15px;
        vertical-align: middle;
        background-color: black;
        border: 1px solid gold;
        font-size: 11px;
    }

    /* On ajoute 138px en largeur */
    .masteries-overlay-6111 {
        top: 10px;
        left: 88px;
    }

    .masteries-overlay-6114 {
        top: 10px;
        left: 148px;
    }

    .masteries-overlay-6311 {
        top: 10px;
        left: 364px;
    }

    .masteries-overlay-6312 {
        top: 10px;
        left: 424px;
    }

    .masteries-overlay-6211 {
        top: 10px;
        left: 640px;
    }

    .masteries-overlay-6212 {
        top: 10px;
        left: 700px;
    }

    /* On descends de 80px */
    .masteries-overlay-6121 {
        top: 90px;
        left: 58px;
    }

    .masteries-overlay-6122 {
        top: 90px;
        left: 118px;
    }

    .masteries-overlay-6123 {
        top: 90px;
        left: 178px;
    }

    .masteries-overlay-6321 {
        top: 90px;
        left: 334px;
    }

    .masteries-overlay-6322 {
        top: 90px;
        left: 394px;
    }

    .masteries-overlay-6323 {
        top: 90px;
        left: 454px;
    }

    .masteries-overlay-6221 {
        top: 90px;
        left: 610px;
    }

    .masteries-overlay-6222 {
        top: 90px;
        left: 670px;
    }

    .masteries-overlay-6223 {
        top: 90px;
        left: 730px;
    }

    /* part 2 */
    /* On ajoute 138px en largeur */
    .masteries-overlay-6131 {
        top: 170px;
        left: 88px;
    }

    .masteries-overlay-6134 {
        top: 170px;
        left: 148px;
    }

    .masteries-overlay-6331 {
        top: 170px;
        left: 364px;
    }

    .masteries-overlay-6332 {
        top: 170px;
        left: 424px;
    }

    .masteries-overlay-6231 {
        top: 170px;
        left: 640px;
    }

    .masteries-overlay-6232 {
        top: 170px;
        left: 700px;
    }

    /* On descends de 80px */
    .masteries-overlay-6141 {
        top: 250px;
        left: 58px;
    }

    .masteries-overlay-6142 {
        top: 250px;
        left: 118px;
    }

    .masteries-overlay-6143 {
        top: 250px;
        left: 178px;
    }

    .masteries-overlay-6341 {
        top: 250px;
        left: 334px;
    }

    .masteries-overlay-6342 {
        top: 250px;
        left: 394px;
    }

    .masteries-overlay-6343 {
        top: 250px;
        left: 454px;
    }

    .masteries-overlay-6241 {
        top: 250px;
        left: 610px;
    }

    .masteries-overlay-6242 {
        top: 250px;
        left: 670px;
    }

    .masteries-overlay-6243 {
        top: 250px;
        left: 730px;
    }

    /* part 3 */
    /* On ajoute 138px en largeur */
    .masteries-overlay-6151 {
        top: 330px;
        left: 88px;
    }

    .masteries-overlay-6154 {
        top: 330px;
        left: 148px;
    }

    .masteries-overlay-6351 {
        top: 330px;
        left: 364px;
    }

    .masteries-overlay-6352 {
        top: 330px;
        left: 424px;
    }

    .masteries-overlay-6251 {
        top: 330px;
        left: 640px;
    }

    .masteries-overlay-6252 {
        top: 330px;
        left: 700px;
    }

    /* On descends de 80px */
    .masteries-overlay-6161 {
        top: 410px;
        left: 58px;
    }

    .masteries-overlay-6162 {
        top: 410px;
        left: 118px;
    }

    .masteries-overlay-6164 {
        top: 410px;
        left: 178px;
    }

    .masteries-overlay-6361 {
        top: 410px;
        left: 334px;
    }

    .masteries-overlay-6362 {
        top: 410px;
        left: 394px;
    }

    .masteries-overlay-6363 {
        top: 410px;
        left: 454px;
    }

    .masteries-overlay-6261 {
        top: 410px;
        left: 610px;
    }

    .masteries-overlay-6262 {
        top: 410px;
        left: 670px;
    }

    .masteries-overlay-6263 {
        top: 410px;
        left: 730px;
    }
</style>

src/AppBundle/Resources/views/Summoner/_live_game_not_found.html.twig
<div>{{ 'live.game.not.found'|trans }}</div>

src/AppBundle/Resources/views/Summoner/_live_game_team_table.html.twig
<table id="{{ teamCSSId }}" class="table table-bordered table-responsive">
    <thead>
    <tr>
        <th class="live-game-name">{{ 'live.game.name'|trans }}</th>
        <th>{{ 'live.game.tier'|trans }}</th>
        <th>{{ 'live.game.stats'|trans }}</th>
        <th class="live-game-champion">{{ 'live.game.champion'|trans }}</th>
        <th>{{ 'live.game.champion.stats'|trans }}</th>
    </tr>
    </thead>
    <tr>
        {% for bannedChampion in bannedChampions %}
            {% if bannedChampion.championId != -1 %}
                <img class="live-game-banned" src="http://ddragon.leagueoflegends.com/cdn/{{ static_data_version }}/img/champion/{{ champions[bannedChampion.championId]['key'] }}.png">
            {% else %}
                <img class="live-game-banned empty-banned-champion" src="{{ asset('bundles/app/images/Unlock_a_Champion.jpg') }}">
            {% endif %}
        {% endfor %}
    </tr>
    {% for player in players %}
        <tr>
            <td><a target="_blank" href="{{ url('app_summoner', {'summonerId': player.summonerId,'region': summoner.region.slug}) }}"><span class="live-game-name">{{ player.summonerName }}</span></a></td>
            <td>
                {% if live_game_data is not empty %}
                    <img class="live-game-rank" src="{{ asset('bundles/app/images/leagues/' ~ live_game_data[player.summonerId].img ~ '.png') }}"/>
                    <span class="live-game-rank">{{ live_game_data[player.summonerId].rank }}</span>
                {% endif %}
            </td>
            <td>
                {% if playerStats[player.summonerId].general is not empty %}
                    {{ playerStats[player.summonerId].general.winrate }} % ({{ playerStats[player.summonerId].general.playedGames }} {{ 'live.game.played'|trans }})<br>
                    {{ playerStats[player.summonerId].general.killsAVG }} / {{ playerStats[player.summonerId].general.deathsAVG }} / {{ playerStats[player.summonerId].general.assistsAVG }}
                {% endif %}
            </td>
            <td>
                <div class="row">
                    <div class="col-md-6">
                        <img class="live-game-champion" src="http://ddragon.leagueoflegends.com/cdn/{{ static_data_version }}/img/champion/{{ champions[player.championId]['key'] }}.png">
                    </div>
                    <div class="col-md-6">
                        <img class="live-game-summoner" src="http://ddragon.leagueoflegends.com/cdn/{{ static_data_version }}/img/spell/{{ summonerSpells[player.spell1Id] }}.png">
                        <img class="live-game-summoner" src="http://ddragon.leagueoflegends.com/cdn/{{ static_data_version }}/img/spell/{{ summonerSpells[player.spell2Id] }}.png">
                    </div>
                </div>
            </td>
            <td>
                {% if playerStats[player.summonerId].champion is not empty %}
                    {{ playerStats[player.summonerId].champion.winrate }} % ({{ playerStats[player.summonerId].champion.playedGames }} {{ 'live.game.played'|trans }})<br>
                    {{ playerStats[player.summonerId].champion.killsAVG }} / {{ playerStats[player.summonerId].champion.deathsAVG }} / {{ playerStats[player.summonerId].champion.assistsAVG }}
                {% endif %}
            </td>
        </tr>
    {% endfor %}
</table>